### ISSUE TITLE
Private repos not listing by default, nor after manually being added.

### ISSUE THREAD

**Issue by blzaugg** [natecavanaugh/github-pulls#3]

**Comment by blzaugg** [comment]
From my Github Profile:

**Personal access tokens**
Github Pulls (by Liferay) - electron — repo
- [x] repo  Full control of private repositories
  - [x] repo:status  Access commit status
  - [x] repo_deployment  Access deployment status
  - [x] public_repo  Access public repositories
- [ ] admin:org  Full control of orgs and teams
  - [ ] write:org  Read and write org and team membership
  - [ ] read:org  Read org and team membership
- [ ] admin:public_key  Full control of user public keys
  - [ ] write:public_key  Write user public keys
  - [ ] read:public_key  Read user public keys
- [ ] admin:repo_hook  Full control of repository hooks
  - [ ] write:repo_hook  Write repository hooks
  - [ ] read:repo_hook  Read repository hooks
- [ ] admin:org_hook  Full control of organization hooks
- [ ] gist  Create gists
- [ ] notifications  Access notifications
- [ ] user  Update all user data
  - [ ] user:email  Access user email addresses (read-only)
  - [ ] user:follow  Follow and unfollow users
- [ ] delete_repo  Delete repositories
- [ ] admin:gpg_key  Full control of user gpg keys (Developer Preview)
  - [ ] write:gpg_key  Write user gpg keys
  - [ ] read:gpg_key  Read user gpg keys

**Comment by blzaugg** [comment]
Jon's looks the same as mine and his lists private repos.

**Comment by natecavanaugh** [comment]
Okay, as mentioned, it might be a UI issue of not informing you that it's only showing repos that have pulls or issues on them. I'll try to think of a better way of communicating it without adding too much noise.

Thanks Byran!

**Comment by blzaugg** [comment]
![hidden](https://cloud.githubusercontent.com/assets/1626739/16425899/8fd17bd8-3d1b-11e6-9cc4-95fa96f5539a.png)

**Comment by natecavanaugh** [comment]
Hmm... that might not be a bad idea. Thanks @blzaugg :)
